del "bundle.js"
type "core\card.js" >> "bundle.js"
echo. >> "bundle.js"
type "core\init.js" >> "bundle.js"
echo. >> "bundle.js"
type "core\link.js" >> "bundle.js"
echo. >> "bundle.js"
type "core\math.js" >> "bundle.js"
echo. >> "bundle.js"
type "core\render.js" >> "bundle.js"
echo. >> "bundle.js"
type "core\state.js" >> "bundle.js"
echo. >> "bundle.js"
type "core\text.js" >> "bundle.js"
echo. >> "bundle.js"
type "games\betrayal.js" >> "bundle.js"
echo. >> "bundle.js"
del "bundle.css"
type "core\style.css" >> "bundle.css"
echo. >> "bundle.css"
type "games\betrayal.css" >> "bundle.css"
echo. >> "bundle.css"