set /A n = 3

del "bundle-*.js"
type "core\card.js" >> "bundle-%n%.js"
echo. >> "bundle-%n%.js"
type "core\init.js" >> "bundle-%n%.js"
echo. >> "bundle-%n%.js"
type "core\link.js" >> "bundle-%n%.js"
echo. >> "bundle-%n%.js"
type "core\math.js" >> "bundle-%n%.js"
echo. >> "bundle-%n%.js"
type "core\render.js" >> "bundle-%n%.js"
echo. >> "bundle-%n%.js"
type "core\state.js" >> "bundle-%n%.js"
echo. >> "bundle-%n%.js"
type "core\text.js" >> "bundle-%n%.js"
echo. >> "bundle-%n%.js"
type "games\Betrayal-2e\game.js" >> "bundle-%n%.js"
echo. >> "bundle-%n%.js"
type "games\Betrayal-2e-dom\game.js" >> "bundle-%n%.js"
echo. >> "bundle-%n%.js"

del "bundle-*.css"
type "core\style.css" >> "bundle-%n%.css"
echo. >> "bundle-%n%.css"
type "games\Betrayal-2e\style.css" >> "bundle-%n%.css"
echo. >> "bundle-%n%.css"